---
apiVersion: v1
kind: CronJob
metadata:
    name: {{ .Values.name }}
spec:
    schedule: "{{ .Values.schedule }}"
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: Never
                    containers:
                        - name: backup-maker
                          image: {{ .Values.image }}
                          imagePullPolicy: Always
                          command:
                              - /bin/bash
                              - /mnt/data/{{ .Values.scriptName }}
                          envFrom:
                              - secretRef:
                                    name: {{ .Values.name }}
                          volumeMounts:
                              - name: data
                                mountPath: /usr/backup-maker
                              - name: secrets
                                mountPath: /mnt/secrets
                    volumes:
                        - name: data
                          configMap:
                              name: {{ .Values.name }}
                        - name: secrets
                          configMap:
                              name: {{ .Values.name }}

                        # todo: Add volumes to values to allow mounting data for copying files
