---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}
data:
    gpg.key: |
        {{- .Values.gpgKeyContent | nindent 8 }}
    {{- if index .Values "env" }}
    {{- with .Values.env }}
    {{- range $key, $value := . }}
    {{ $key }}: |
        {{- $value | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- end }}
